server:
  port: 9090

resilience4j.circuitbreaker:
  configs:
    default:
        # 최근 10개 요청 중 응답속도가 1초 초과한 비율이 70% 이상일때 Circuit Breaker OPEN
        # 단, 5개 요청까지는 OPEN하지 않음. http timeout정책은 resilience.circuitbreaker.timeout 참조
        # slowCallDurationThreshold값은 http timeout시간보다 작아야 제대로 동작함. 크면, timeout이 먼저 발생하므로 의미가 없음.
        slidingWindowType: COUNT_BASED           # default: COUNT_BASED
        slidingWindowSize: 10                    # {통계건수}  default: 100
        minimumNumberOfCalls: 2                  # {최소요청횟수 default: 100 }
        failureRateThreshold: 50                 # {실패율 default: 50 }
        waitDurationInOpenState: 3000           # {Circuit Breaker유지시간 default: 60000 }
    instances:
      mycb:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger{36}.%method:%line] - %msg%n"

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          demo-client:
            provider: keycloak
            client-id: demo-client
            client-secret: 061e52a9-8e2c-4687-8d75-ecd87f769230
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: demo-fe-board
          uri: http://localhost:8088/
          predicates:
            - name: Path
              args:
                patterns: /boards/**
            - name: Method
              args:
                methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: mycb
                fallbackUri: forward:/fallback    # fallback은 Circuit 상태와 상관 없이, fail조건에 해당된 경우 호출됨
          metadata:
            connect-timeout: 2500
            response-timeout: 2500

        - id: demo-fe-api
          uri: http://localhost:8088/
          predicates:
            - Path=/api/**




