apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-scg-configmap
  namespace: gateway
data:
  application.yaml: |
    resilience4j.circuitbreaker:
      configs:
        default:
          slidingWindowType: COUNT_BASED           
          slidingWindowSize: 10              
          minimumNumberOfCalls: 2               
          failureRateThreshold: 50               
          waitDurationInOpenState: 3000      
        instances:
          mycb:
            baseConfig: default
    
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        shutdown:
          enabled: true
        health:
          show-details: always
      health:
        circuitbreakers:
          enabled: true
    
    
    logging:
      level:
        org.springframework.cloud.gateway: DEBUG
        reactor.netty.http.client: DEBUG
      pattern:
        console: "[%d{HH:mm:ss.SSS}][%-5level][%logger{36}.%method:%line] - %msg%n"
    
    spring:
      profiles.active: dev
      security:
        oauth2:
          client:
            provider:
              keycloak:
                token-uri: http://host.docker.internal:8080/auth/realms/demo/protocol/openid-connect/token
                authorization-uri: http://host.docker.internal:8080/auth/realms/demo/protocol/openid-connect/auth
                userinfo-uri: http://host.docker.internal:8080/auth/realms/demo/protocol/openid-connect/userinfo
                user-name-attribute: preferred_username
            registration:
              demo-client:
                provider: keycloak
                client-id: demo-client
                client-secret: 83f3e948-3f8c-49da-af7f-87a42d5ea6fd
                authorization-grant-type: authorization_code
                redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
    
    
      cloud:
        gateway:
          default-filters:
            - TokenRelay
          routes:
            - id: demo-fe-board
              uri: http://demo-fe-svc.fe.svc.cluster.local:8080
              predicates:
                - name: Path
                  args:
                    patterns: /boards/**
                - name: Method
                  args:
                    methods:
                      - GET
                      - POST
                      - PUT
                      - DELETE
    
            - id: demo-fe-api
              uri: http://demo-fe-svc.fe:8080/
              predicates:
                - Path=/api/**
