##  Check the permission of the service account(default) used by spring boot app
# kubectl auth can-i get configmap --as=system:serviceaccount:gateway:default -n gateway
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: gateway
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: gateway
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""